Message:
  Title: "&b[MobDrop2] "
  MobDropItem: "§f%mob% §6dropped §f%item% §6X §b%item_num% §6!"
  Gobal_MobDropItem: "§6Congratulations! §a%player% §6kill§f %mob% §6and drops §a%item% §6X §b%item_num% §6!"
  Data_Re_read: "Re-read Data..."
  Data_Re_read_Complete: "Read Complete"

SQL:
  Join_db_connect_error: "&c伺服器連接資料庫失敗，無法使用此功能，請立即連絡管理員"
  DataBase_URL: "&a資料庫的連結網址%URL%"
  DataBase_is_connect: "&aDataBase is connect"
  DataBase_Connecting: "&aConnecting to database..."
  DataBase_Close: "&aDataBase connect is close"
  DataBase_Creating: "&aCreating database..."
  DataBase_Create_Success: "&aDatabase created successfully"
  DataBase_Reconnecting: "&c重新連結資料庫..."
  DataBase_Selecting: "&aSelect database【 &e%db% &a】..."
  DataBase_Select_Success: "&aDatabase【 &e%db% &a】Select successfully"
  DataBase_Select_Fail: "&cDataBase【 &e%db% &a】Select Fail"
  Table_Createing: "&aCreate table【 &e%table% &a】in database【&e%db% &a】..."
  Table_Create_Success: "&aTable【 &e%table% &a】has been successfully created in【 &e%db% &a】database"
  Table_Create_Fail: "&cTable【 &e%table% &c】failed to create in【 &e%db% &c】database"
  Run_cmd: "&aSQL Command:"
  Run_cmd_color: "&2"
  Run_cmd_Success: "&aCommand executed successfully"
  Run_cmd_fail: "&aCommand execution failed"
  Connecting_fail: "&cDataBase Connect Fail"
  can_not_use_command: "&c無法使用此指令【%cmd%】,連結取消"

Timer:
  TimeStart: "&a請於 %time% 秒內完成輸入!"
  TimeOut: "&c %time% 秒的時間已到"
  TimeLeft:
    - "&c還剩餘 %%10%% 秒能輸入"
    - "&c還剩餘  %%5%% 秒能輸入"
    - "&c還剩餘  %%4%% 秒能輸入"
    - "&c還剩餘  %%3%% 秒能輸入"
    - "&c還剩餘  %%2%% 秒能輸入"
    - "&c還剩餘  %%1%% 秒能輸入"

Inventory:
  Material_not_found: "&c找不到適當的材料"
  Button_not_found: "&c找不到按鍵"
  Button_not_found_lore: "&c找不到按鍵,請聯絡管理員"
  Title_error: "&c標題讀取錯誤,請聯絡管理員"
  Type_error: "&c圖示讀取錯誤,請聯絡管理員"
  items_table_get_item_info:
    - ""
    - "&aLeft click"
    - "&aTake this Item"
  items_table_get_item_success: "&f獲取道具ID:&6%id% &f, 名稱:%name%"
  items_table_get_item_bag_full: "&c背包已滿，無法獲取道具"
  items_table_add_success: "&a物品增加成功"
  items_table_add_fail: "&c物品增加失敗"
  mob_remove_msg: "&b刪除怪物 '&6%mobname%&b'"
  mob_name_noset_error: "&c名稱不能是空白"
  mob_name_same_error: "&c怪物名稱重複"
  mob_normal_no_select: "&c請選擇怪物"
  mob_normal_same_select: "&c系統內已有重複怪物"
  mob_item_noset_error: "&c請選擇物品"
  mob_item_same_error: "&c此怪物已有重複物品"
  mob_item_remove_msg: "&b刪除怪物 '&6%mobname%&b' 的物品 '&6%itemname%&b'(&7%itemno%&b)"
  mob_item_edit_info:
    - ""
    - "&aLeft click"
    - "&aEdit Item"
  mob_info_lore:
    - ""
    - "&7Items: &2%num%"
  dropitem_info_lore:
    - ""
    - "&7Chance: &2%Chance%%"
    - "&7Quantity: &2%Quantity%"

Command:
  CmdCanNotUse: "&cYou Can not use this command here"
  PlayerCanNotUse: "&cYou can't use this command"
  NoPermission: "&cYou don't have this permission"
  CanNotFind: "&cUnknown Command"
  HandNoItem: "&cNo Item on hand"
  ItemNotFind: "&cUnknown Item"
  
Mobs:
  #1.13
  BAT: "Bat"
  BLAZE: "Blaze"
  CAVE_SPIDER: "Cave Spider"
  CHICKEN: "Chicken"
  COD: "Cod"
  COW: "Cow"
  CREEPER: "Creeper"
  DOLPHIN: "Dolphin"
  DONKEY: "Donkey"
  DROWNED: "Drowned"
  ELDER_GUARDIAN: "Elder Guardian"
  ENDERMAN: "Enderman"
  ENDERMITE: "Endermite"
  ENDER_DRAGON: "Ender Dragon"
  EVOKER: "Evoker"
  GHAST: "Ghast"
  GIANT: "Giant"
  GUARDIAN: "Guardian"
  HORSE: "Horse"
  HUSK: "Husk"
  ILLUSIONER: "Illusioner"
  IRON_GOLEM: "Iron Golem"
  LLAMA: "Llama"
  MAGMA_CUBE: "Magma Cube"
  MUSHROOM_COW: "Mushroom Cow"
  MULE: "Mule" 
  OCELOT: "Ocelot"
  PARROT: "Parrot"
  PHANTOM: "Phantom"
  PIG: "Pig"
  PIG_ZOMBIE: "Pig Zombie"
  POLAR_BEAR: "Polar Bear"
  PUFFERFISH: "Pufferfish"
  RABBIT: "Rabbit"
  SALMON: "Salmon"
  SHEEP: "Sheep"
  SHULKER: "Shulker"
  SILVERFISH: "Silverfish"
  SKELETON: "Skeleton"
  SKELETON_HORSE: "Skeleton Horse"
  SLIME: "Slime"
  SNOWMAN: "Snowman"
  SPIDER: "Spider"
  SQUID: "Squid"
  STRAY: "Stray"
  TROPICAL_FISH: "Tropical Fish"
  TURTLE: "Turtle"
  VEX: "Vex"
  VILLAGER: "Villager"
  VILLAGERGOLEM: "VillagerGolem"
  VINDICATOR: "Vindicator"
  WITCH: "Witch"
  WITHER_SKELETON: "Witch Skeleton"
  WITHER_SKULL: "Witch Skull"
  WOLF: "Wolf"
  ZOMBIE: "Zombie"
  ZOMBIE_HORSE: "Zombie Horse"
  ZOMBIE_PIGMAN: "Zombie Pigman"
  ZOMBIE_VILLAGER: "Zombie Villager"
  # 1.14
  CAT: "Cat"
  FOX: "Fox"
  PANDA: "Panda"
  PILLAGER: "Pillager"
  RAVAGER: "Ravager"
  TRADER_LLAMA: "Trader Llama"
  WANDERING_TRADER: "Wandering Trader"
  # 1.15
  BEE: "Bee"
  # 1.16
  HOGLIN: "Hoglin"
  PIGLIN: "Piglin"
  STRIDER: "Strider"
  ZOGLIN: "Zoglin"
  ZOMBIFIED_PIGLIN: "Zombified Piglin"
  # 1.16.2
  PIGLIN_BRUTE: "Piglin Brute"
  # 1.17
  AXOLOTL: "AXOLOTL"
  GLOW_SQUID: "Glow Squid"
  GOAT: "Goat"