name: MobDrop2
main: com.brian.MobDrop2.MobDrop2
version: ${full.version}
author: 0obrino0
website: www.youtube.com/user/brian041301
api-version: 1.13
depend: [SmartInvs]
commands:
   mobdrop:
      description: mobdrop Commands.
   mobdrop2:
      description: mobdrop Commands.
   mdop:
      description: mobdrop Commands.
permissions:
   mobdrop.*:
      default: op
      description: Give players with op everything by default
      children:
         mobdrop.user.*: true
         mobdrop.admin.*: true
   mobdrop.user.*:
      default: true
      children:
         mobdrop.user: true
         mobdrop.user.help: true
         mobdrop.user.inventory.*: true
   mobdrop.user.inventory.*:
      default: true
      children:
         mobdrop.user.inventory.menu: true
   mobdrop.admin.*:
      default: op
      children:
         mobdrop.admin: true
         mobdrop.admin.items.*: true
         mobdrop.admin.itemset.*: true
         mobdrop.admin.reload: true
         mobdrop.admin.test: true
         mobdrop.admin.inventory.*: true
   mobdrop.admin.items.*:
      default: op
      children:
         mobdrop.admin.items.add: true
         mobdrop.admin.items.get: true
         mobdrop.admin.items.remove: true
   mobdrop.admin.itemset.*:
      default: op
      children:
         mobdrop.admin.itemset.name: true
         mobdrop.admin.itemset.addlore: true
         mobdrop.admin.itemset.durability: true
         mobdrop.admin.itemset.amount: true
   mobdrop.admin.inventory.*:
      default: op
      children:
         mobdrop.admin.inventory.items.*: true
         mobdrop.admin.inventory.mob.*: true
   mobdrop.admin.inventory.items.*:
      default: op
      children:
         mobdrop.admin.inventory.items.get: true
   mobdrop.admin.inventory.mob.*:
      default: op
      children:
         mobdrop.admin.inventory.mod.add: true
         mobdrop.admin.inventory.mob.edit: true
         mobdrop.admin.inventory.mod.remove: true
         mobdrop.admin.inventory.mob.item.*: true
   mobdrop.admin.inventory.mob.item.*:
      default: op
      children:
        mobdrop.admin.inventory.mob.item.add: true